import { Center } from '@chakra-ui/react';
import Head from 'next/head';
import { CustProductCard } from '~/components/CustProductCard';

import { api } from '~/utils/api';

export default function Customer() {
  const ctx = api.useUtils();
  const { data } = api.product.getAll.useQuery();
  const { mutate } = api.product.delete.useMutation({
    onSuccess: () => {
      void ctx.product.getAll.invalidate();
    }
  });

  return (
    <>
      <Head>
        <title>Shopping Page 🛒</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          Customer shopping page!!!!!!
        </div>
        <Center>
          {data?.map((data) => (
            <CustProductCard
              product={data}
              key={data.product_id}
              onDelete={() => {
                mutate({ id: data.product_id });
              }}
            />
          ))}
        </Center>
      </main>
    </>
  );
}
