import { Flex } from '@chakra-ui/react';
import Head from 'next/head';
import { AddressCard } from '~/components/AddressCard';
import { CreditCardCard } from '~/components/CreditCardCard';
import { api } from '~/utils/api';

//Lists all addresses
//Lists all Credit cards

export default function Account(){
    const ctx = api.useUtils();
  const { data: CreditCardData } = api.CreditCard.getAll.useQuery();
  const { data: Addressdata } = api.Address.getAll.useQuery();
  const { mutate } = api.product.delete.useMutation({
    onSuccess: () => {
      void ctx.CreditCard.getAll.invalidate();
      void ctx.Address.getAll.invalidate();
    }
  });

    return(
        <>
      <Head>
        <title>Account Settings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Addresses:</h2>
        </div>
        <Flex flexWrap="wrap" justifyContent="flex-start">
          {Addressdata?.map((Address) => (
            <AddressCard
              customer_address = {Address}
              key={Address.cust_address_id}
              onDelete={() => {
                mutate({ id: Address.cust_address_id });
              }}
            />
          ))}
        </Flex>
        <div>
          <h2>Credit Cards:</h2>
        </div>
        <Flex flexWrap="wrap" justifyContent="flex-start">
          {CreditCardData?.map((CreditCard) => (
            <CreditCardCard
              Credit_Card = {CreditCard}
              key={CreditCard.card_id}
              onDelete={() => {
                mutate({ id: CreditCard.card_id });
              }}
            />
          ))}
        </Flex>
      </main>
    </>
    );
}