import { Flex } from '@chakra-ui/react';
import Head from 'next/head';
import { AddressCard } from '~/components/AddressCard';
import { CreditCardCard } from '~/components/CreditCardCard';
import { api } from '~/utils/api';

//Lists all addresses
//Lists all Credit cards

export default function Account(){
    const ctx = api.useUtils();
  const { Address_data } = api.credit_card.getAll.useQuery();
  const { credit_card_data } = api.credit_card.getAll.useQuery();
  const { mutate } = api.product.delete.useMutation({
    onSuccess: () => {
      void ctx.credit_card.getAll.invalidate();
    }
  });

    return(
        <>
      <Head>
        <title>Account Settings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Addresses:</h2>
        </div>
        <Flex flexWrap="wrap" justifyContent="flex-start">
          {data?.map((data) => (
            <AddressCard
              product={data}
              key={data.product_id}
              onDelete={() => {
                mutate({ id: data.product_id });
              }}
            />
          ))}
        </Flex>
        <div>
          <h2>Credit Cards:</h2>
        </div>
        <Flex flexWrap="wrap" justifyContent="flex-start">
          {data?.map((data) => (
            <CreditCardCard
              product={data}
              key={data.product_id}
              onDelete={() => {
                mutate({ id: data.product_id });
              }}
            />
          ))}
        </Flex>
      </main>
    </>
    );
}